// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.19.4
// source: ds/dsdata.proto

package ds

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DataBlob struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Keys              []*HiddenDataKey `protobuf:"bytes,1,rep,name=keys,proto3" json:"keys,omitempty"`
	DataLen           uint64           `protobuf:"varint,10,opt,name=dataLen,proto3" json:"dataLen,omitempty"`                    // EncryptedData might be padded
	Iv                []byte           `protobuf:"bytes,12,opt,name=iv,proto3" json:"iv,omitempty"`                               // 16 bytes
	EncryptedDataHash []byte           `protobuf:"bytes,11,opt,name=encryptedDataHash,proto3" json:"encryptedDataHash,omitempty"` // To check data integrity
	// The data is encrypted by a single data_key.
	// The hidden key is encrypted by secrets that are only retrievable by corresponding pubkey-privkey pair owner.
	EncryptedData []byte `protobuf:"bytes,20,opt,name=encryptedData,proto3" json:"encryptedData,omitempty"`
}

func (x *DataBlob) Reset() {
	*x = DataBlob{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ds_dsdata_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DataBlob) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DataBlob) ProtoMessage() {}

func (x *DataBlob) ProtoReflect() protoreflect.Message {
	mi := &file_ds_dsdata_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DataBlob.ProtoReflect.Descriptor instead.
func (*DataBlob) Descriptor() ([]byte, []int) {
	return file_ds_dsdata_proto_rawDescGZIP(), []int{0}
}

func (x *DataBlob) GetKeys() []*HiddenDataKey {
	if x != nil {
		return x.Keys
	}
	return nil
}

func (x *DataBlob) GetDataLen() uint64 {
	if x != nil {
		return x.DataLen
	}
	return 0
}

func (x *DataBlob) GetIv() []byte {
	if x != nil {
		return x.Iv
	}
	return nil
}

func (x *DataBlob) GetEncryptedDataHash() []byte {
	if x != nil {
		return x.EncryptedDataHash
	}
	return nil
}

func (x *DataBlob) GetEncryptedData() []byte {
	if x != nil {
		return x.EncryptedData
	}
	return nil
}

type HiddenDataKey struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Pubkey          []byte `protobuf:"bytes,1,opt,name=pubkey,proto3" json:"pubkey,omitempty"`
	EphemeralPubkey []byte `protobuf:"bytes,2,opt,name=ephemeralPubkey,proto3" json:"ephemeralPubkey,omitempty"`
	// SharedSecret = privkey * ephemeral_privkey * Generator = privkey * ephemeralPubkey
	// encryptedKey = AES_ENCRYPT(key=sha256(SharedSecret)[:128], iv=iv, data=data_key)
	EncryptedHiddenKey []byte `protobuf:"bytes,10,opt,name=encryptedHiddenKey,proto3" json:"encryptedHiddenKey,omitempty"` // AES_128 encryption
	Iv                 []byte `protobuf:"bytes,11,opt,name=iv,proto3" json:"iv,omitempty"`                                 // 16 bytes
}

func (x *HiddenDataKey) Reset() {
	*x = HiddenDataKey{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ds_dsdata_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HiddenDataKey) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HiddenDataKey) ProtoMessage() {}

func (x *HiddenDataKey) ProtoReflect() protoreflect.Message {
	mi := &file_ds_dsdata_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HiddenDataKey.ProtoReflect.Descriptor instead.
func (*HiddenDataKey) Descriptor() ([]byte, []int) {
	return file_ds_dsdata_proto_rawDescGZIP(), []int{1}
}

func (x *HiddenDataKey) GetPubkey() []byte {
	if x != nil {
		return x.Pubkey
	}
	return nil
}

func (x *HiddenDataKey) GetEphemeralPubkey() []byte {
	if x != nil {
		return x.EphemeralPubkey
	}
	return nil
}

func (x *HiddenDataKey) GetEncryptedHiddenKey() []byte {
	if x != nil {
		return x.EncryptedHiddenKey
	}
	return nil
}

func (x *HiddenDataKey) GetIv() []byte {
	if x != nil {
		return x.Iv
	}
	return nil
}

var File_ds_dsdata_proto protoreflect.FileDescriptor

var file_ds_dsdata_proto_rawDesc = []byte{
	0x0a, 0x0f, 0x64, 0x73, 0x2f, 0x64, 0x73, 0x64, 0x61, 0x74, 0x61, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x17, 0x6a, 0x69, 0x6e, 0x66, 0x77, 0x68, 0x75, 0x61, 0x6e, 0x67, 0x2e, 0x64, 0x73,
	0x74, 0x6f, 0x6f, 0x6c, 0x6b, 0x69, 0x74, 0x2e, 0x64, 0x73, 0x1a, 0x1c, 0x67, 0x6f, 0x6f, 0x67,
	0x6c, 0x65, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x61, 0x6e, 0x6e, 0x6f, 0x74, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1b, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65,
	0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x65, 0x6d, 0x70, 0x74, 0x79, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xc4, 0x01, 0x0a, 0x08, 0x44, 0x61, 0x74, 0x61, 0x42, 0x6c,
	0x6f, 0x62, 0x12, 0x3a, 0x0a, 0x04, 0x6b, 0x65, 0x79, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x26, 0x2e, 0x6a, 0x69, 0x6e, 0x66, 0x77, 0x68, 0x75, 0x61, 0x6e, 0x67, 0x2e, 0x64, 0x73,
	0x74, 0x6f, 0x6f, 0x6c, 0x6b, 0x69, 0x74, 0x2e, 0x64, 0x73, 0x2e, 0x48, 0x69, 0x64, 0x64, 0x65,
	0x6e, 0x44, 0x61, 0x74, 0x61, 0x4b, 0x65, 0x79, 0x52, 0x04, 0x6b, 0x65, 0x79, 0x73, 0x12, 0x18,
	0x0a, 0x07, 0x64, 0x61, 0x74, 0x61, 0x4c, 0x65, 0x6e, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x04, 0x52,
	0x07, 0x64, 0x61, 0x74, 0x61, 0x4c, 0x65, 0x6e, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x76, 0x18, 0x0c,
	0x20, 0x01, 0x28, 0x0c, 0x52, 0x02, 0x69, 0x76, 0x12, 0x2c, 0x0a, 0x11, 0x65, 0x6e, 0x63, 0x72,
	0x79, 0x70, 0x74, 0x65, 0x64, 0x44, 0x61, 0x74, 0x61, 0x48, 0x61, 0x73, 0x68, 0x18, 0x0b, 0x20,
	0x01, 0x28, 0x0c, 0x52, 0x11, 0x65, 0x6e, 0x63, 0x72, 0x79, 0x70, 0x74, 0x65, 0x64, 0x44, 0x61,
	0x74, 0x61, 0x48, 0x61, 0x73, 0x68, 0x12, 0x24, 0x0a, 0x0d, 0x65, 0x6e, 0x63, 0x72, 0x79, 0x70,
	0x74, 0x65, 0x64, 0x44, 0x61, 0x74, 0x61, 0x18, 0x14, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x0d, 0x65,
	0x6e, 0x63, 0x72, 0x79, 0x70, 0x74, 0x65, 0x64, 0x44, 0x61, 0x74, 0x61, 0x22, 0x91, 0x01, 0x0a,
	0x0d, 0x48, 0x69, 0x64, 0x64, 0x65, 0x6e, 0x44, 0x61, 0x74, 0x61, 0x4b, 0x65, 0x79, 0x12, 0x16,
	0x0a, 0x06, 0x70, 0x75, 0x62, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x06,
	0x70, 0x75, 0x62, 0x6b, 0x65, 0x79, 0x12, 0x28, 0x0a, 0x0f, 0x65, 0x70, 0x68, 0x65, 0x6d, 0x65,
	0x72, 0x61, 0x6c, 0x50, 0x75, 0x62, 0x6b, 0x65, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52,
	0x0f, 0x65, 0x70, 0x68, 0x65, 0x6d, 0x65, 0x72, 0x61, 0x6c, 0x50, 0x75, 0x62, 0x6b, 0x65, 0x79,
	0x12, 0x2e, 0x0a, 0x12, 0x65, 0x6e, 0x63, 0x72, 0x79, 0x70, 0x74, 0x65, 0x64, 0x48, 0x69, 0x64,
	0x64, 0x65, 0x6e, 0x4b, 0x65, 0x79, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x12, 0x65, 0x6e,
	0x63, 0x72, 0x79, 0x70, 0x74, 0x65, 0x64, 0x48, 0x69, 0x64, 0x64, 0x65, 0x6e, 0x4b, 0x65, 0x79,
	0x12, 0x0e, 0x0a, 0x02, 0x69, 0x76, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x02, 0x69, 0x76,
	0x42, 0x2b, 0x5a, 0x29, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6a,
	0x69, 0x6e, 0x66, 0x77, 0x68, 0x75, 0x61, 0x6e, 0x67, 0x2f, 0x64, 0x73, 0x2d, 0x74, 0x6f, 0x6f,
	0x6c, 0x6b, 0x69, 0x74, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x64, 0x73, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_ds_dsdata_proto_rawDescOnce sync.Once
	file_ds_dsdata_proto_rawDescData = file_ds_dsdata_proto_rawDesc
)

func file_ds_dsdata_proto_rawDescGZIP() []byte {
	file_ds_dsdata_proto_rawDescOnce.Do(func() {
		file_ds_dsdata_proto_rawDescData = protoimpl.X.CompressGZIP(file_ds_dsdata_proto_rawDescData)
	})
	return file_ds_dsdata_proto_rawDescData
}

var file_ds_dsdata_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_ds_dsdata_proto_goTypes = []interface{}{
	(*DataBlob)(nil),      // 0: jinfwhuang.dstoolkit.ds.DataBlob
	(*HiddenDataKey)(nil), // 1: jinfwhuang.dstoolkit.ds.HiddenDataKey
}
var file_ds_dsdata_proto_depIdxs = []int32{
	1, // 0: jinfwhuang.dstoolkit.ds.DataBlob.keys:type_name -> jinfwhuang.dstoolkit.ds.HiddenDataKey
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_ds_dsdata_proto_init() }
func file_ds_dsdata_proto_init() {
	if File_ds_dsdata_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_ds_dsdata_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DataBlob); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ds_dsdata_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HiddenDataKey); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_ds_dsdata_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_ds_dsdata_proto_goTypes,
		DependencyIndexes: file_ds_dsdata_proto_depIdxs,
		MessageInfos:      file_ds_dsdata_proto_msgTypes,
	}.Build()
	File_ds_dsdata_proto = out.File
	file_ds_dsdata_proto_rawDesc = nil
	file_ds_dsdata_proto_goTypes = nil
	file_ds_dsdata_proto_depIdxs = nil
}
